Display:
  Color: black
  Label: ffffff
  ChromaKey: 00ff00
Twitch:
  ClientId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  ClientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  Channel: MyTwitchChannel
OBS:
  Scene: _Dice
  Host: 127.0.0.1
  Port: 4455
  Password: xxxxxxxxxxxxxxx
Commands:
  - Name: roll
    Dice: 1d20
    Message: '{user} rolled {result}'
    DisplayTime: 5
  - Name: percent
    Dice: 1d100+1d10
    Message: '{user} rolled {result}%'
    DisplayTime: 5
  - Name: yo
    Script: |
      await message.reply("Yo!")
